---
Name: innoweb-robots
---
Page:
  extensions:
    - Innoweb\Robots\Extensions\PageExtension
  robots_enable_metatag: true
  robots_noindex: false
  robots_nofollow: false

SilverStripe\CMS\Model\VirtualPage:
  robots_noindex: true
  robots_nofollow: true

SilverStripe\ErrorPage\ErrorPage:
  robots_noindex: true
  robots_nofollow: true

---
Name: innoweb-robots-multisites
Only:
  moduleexists: 'symbiote/silverstripe-multisites'
---
Symbiote\Multisites\Model\Site:
  extensions:
    innowebRobotsConfig: Innoweb\Robots\Extensions\ConfigExtension

---
Name: innoweb-robots-configured-multisites
Only:
  moduleexists: 'fromholdio/silverstripe-configured-multisites'
---

Fromholdio\ConfiguredMultisites\Model\Site:
  extensions:
    innowebRobotsConfig: Innoweb\Robots\Extensions\ConfigExtension

---
Name: innoweb-robots-nomultisites
Except:
  moduleexists:
    - 'symbiote/silverstripe-multisites'
    - 'fromholdio/silverstripe-configured-multisites'
---
Silverstripe\SiteConfig\SiteConfig:
  extensions:
    innowebRobotsConfig: Innoweb\Robots\Extensions\ConfigExtension
